config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :site_informations
  end
  namespace :admin do
    resources :supporting_units
  end
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  namespace :admin do
    resources :pages do
        get :move
    end
    resources :pages
    resources :survey_templates do
      get :toggle_default
    end
    resources :labels
    resources :users do
      get :toggle_admin
    end
    get '', to: 'dashboard#index', as: '/'
    resource :broken_link do
      get :runReport
    end
    resources :site_informations do
      get :toggle_maintenance_mode
    end
  end

  resources :sessions
  resources :omniauth_callbacks, only: :index do
    collection do
      get :single_logout
    end
  end

  resources :pages, :except => ['edit', 'new', 'update', 'destroy']
  resources :users do
    resources :surveys, :path => 'views' do
      get :toggle_default
    end
  end
  get 'sitemap', to:'pages#sitemap', as: 'sitemap'
  match  '/auth/:provider/callback', :to => 'omniauth_callbacks#saml', via: [:get, :post]
  match  'pages/auth/:provider/callback', :to => 'omniauth_callbacks#saml', via: [:get, :post]
  root 'pages#index'
  get '/search' => 'pages#search'
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  # the content is mandatory
  validates_presence_of :content

  belongs_to :question
  has_and_belongs_to_many :surveys
  has_many :answers_labels, :class_name => 'AnswersLabel'
  has_and_belongs_to_many :labels
  # has_many :labels, through: :answers_labels

end

app/models/answers_label.rb
class AnswersLabel < ApplicationRecord
  belongs_to :labels
  belongs_to :answers

end

app/models/answers_survey.rb
class AnswersSurvey < ApplicationRecord
  belongs_to :surveys
  belongs_to :answers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  # has_and_belongs_to_many :pages, dependent: :destroy
  has_many :answers_label, :class_name => 'AnswersLabel'
  has_many :answers, through: :answers_label

  validates_uniqueness_of :name, :message => '%{value} has already been taken'
end

app/models/labels_page.rb
class LabelsPage < ApplicationRecord
  belongs_to :labels
  belongs_to :pages
end

app/models/page.rb
class Page < ApplicationRecord
  has_ancestry :cache_depth => true
  acts_as_list scope: [:ancestry]
  has_and_belongs_to_many :labels

  def self.search(search)
    where("header LIKE ? OR title LIKE ? OR body LIKE ?", "%#{search}%", "%#{search}%" ,"%#{search}%")
  end

end

app/models/question.rb
class Question < ApplicationRecord
  # the content is mandatory
  validates_presence_of :content
  validates_presence_of :answers
  
  has_many :answers, dependent: :destroy
  belongs_to :survey_template
  belongs_to :question_type
  accepts_nested_attributes_for :answers, allow_destroy: true
end

app/models/question_type.rb
class QuestionType < ApplicationRecord
  has_one :question
end

app/models/survey.rb
class Survey < ApplicationRecord
  # the name is mandatory
  validates_presence_of :name

  belongs_to :user
  belongs_to :survey_template
  has_and_belongs_to_many :answers
end

app/models/survey_template.rb
class SurveyTemplate < ApplicationRecord
  # the name is mandatory
  validates_presence_of :name
  validates_presence_of :questions

  has_many :questions, dependent: :destroy
  has_many :surveys

  has_many :answers_label

  accepts_nested_attributes_for :questions, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :surveys

  def name
    first_name + " " + last_name
  end
end

app/helpers/admin_helper.rb
module AdminHelper
  def cp(path)
    "current" if current_page?(path)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def nested_pages(pages)
    pages.map do |page, sub_pages|
      render(page) + nested_pages(sub_pages)
    end.join.html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/pages/_form.html.erb
<% if @page.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@@page.errors.count, "error") %> prohibited this @page from being saved:</h2>

    <ul>
    <% @@page.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form.hidden_field :parent_id %>

<div class="field">
  <%= label_tag(:title, "Page Title:", :class => 'label') %>
  <div class="control">
    <%= form.text_field :title %>
  </div>
</div>

<div class="field">
  <%= label_tag(:header, "Page Header:", :class => 'label') %>
  <div class="control">
    <%= form.text_field :header %>
  </div>
</div>

<div class="field">
  <%= label_tag(:parent_id, "Parent Page:", :class => 'label') %>
  <div class="select">
    <%= form.select :parent_id,
    options_from_collection_for_select(Page.where("ancestry_depth < 4").all, :id, :title, @page.parent_id),
      { include_blank: 'No Parent' },
      { class: 'select' }
      %>
  </div>
</div>

<!-- <div class="field">
  <%= label_tag(:is_numbered, "Numbered Section?", :class => 'label') %>
  <%= form.check_box :is_numbered %> <br />
</div> -->

<div class="field">
  <%= label_tag(:body, "Page Body:", :class => 'label') %>
  <%= form.trix_editor :body %>
</div>

<div class="field">
  <%= label_tag(:alwaysShow, "When Should this Page Be Displayed?", :class => 'label') %>
  <div class="select">
    <%= form.select :alwaysShow, [['Only for Selected Labels', false], ['Always', true]] %>
  </div>
</div>
<div id="label-container" class="label-container">
  <div class="field">
    <%= label_tag(:label, "Labels:", :class => 'label adjusted-top') %>
    <div id="label-list">
      <%= form.collection_check_boxes :label_ids, Label.all, :id, :name do |b| %>
        <div class="collection-check-box">
          <%= b.label %>
          <%= b.check_box %>
        </div>
      <% end %>
    </div>
  </div>
  <%= button_tag("New Label", :type=> 'button', :class => 'add-label-modal button is-warning is-add large-button') %>
</div>

<div class="field">
  <div class="control">
    <%= form.submit 'Submit', :class => 'button is-warning is-add' %>
  </div>
</div>

app/views/admin/pages/_label_modal.html.erb
<div id="add-label" class="modal">
    <div class="modal-background"></div>
    <div class="modal-card">
      <header class="modal-card-head">
        <p class="modal-card-title">New Label</p>
        <button class="delete" aria-label="close"></button>
      </header>
      <div class="modal-card-body">
        <%= form_for [:admin, @label], remote: true do |builder| %>
          <%= render '/admin/labels/form', form: builder %>
        <% end %>
      </div>
    </div>
</div>

app/views/admin/pages/_page.html.erb
<tr>
  <td class='nested<%= page.ancestry_depth %>' data-label="Page Title">
    <%= page.title %>
  </td>
  <td data-label="Modified Date">
    <%= page.updated_at.strftime('%m/%d/%y')   %>
  </td>
  <td data-label="Position">
    <div class="position"><%= page.position %></div>
    <div class="controls">
      <% if page.position != 1 %>
        <%= link_to "", {:controller => "admin/pages", :action => "move", :method => "move_higher", :page_id => page.id }, :class => 'control up'%>
      <% end %>
      <% if page.position != page.siblings.count %>
        <%= link_to "", {:controller => "admin/pages", :action => "move", :method => "move_lower", :page_id => page.id }, :class => 'control down'%>
      <% end %>
    </div>
  </td>
  <td>
    <% if page.ancestry_depth < 4 %>
      <%= link_to 'Child', new_admin_page_path(:parent_id => page), :class => 'button is-warning is-add large-button' %>
    <% end %>
  </td>
  <td>
    <%= link_to 'View', page_path(page), :class => 'button is-show is-primary large-button' %>
    <%= link_to 'Edit', edit_admin_page_path(page), :class => 'button is-edit is-gray large-button'  %>
    <%= link_to 'Delete', admin_page_path(page), method: :delete, data: { confirm: 'If any children pages exist, they will also be removed. Are you sure you want to delete this page? ' }, :class => 'button is-delete is-red large-button'  %>
  </td>


</tr>

app/views/admin/pages/edit.html.erb
<h1 class="title">Editing Page <%= link_to 'Back to All Pages', admin_pages_path, :class => 'button is-blue is-back is-pulled-right large-button' %></h1>

<%= render 'label_modal' %>

<%= form_for @page, url: admin_page_path(@page) do |form| %>
  <%= render 'form', form: form %>
<% end %>

app/views/admin/pages/index.html.erb
<% if notice %>
<p id="notice" class="notification is-success"><%= notice %></p>
<% end %>
<h1 class="title">Pages <%= link_to 'New Page', new_admin_page_path, :class => 'button is-add is-warning large-button is-pulled-right' %></h1>
<table class="pages table is-striped">
  <thead>
    <th>Page Title</th>
    <th width="15%">Modified Date</th>
    <th width="15%">Position</th>
    <th width="15%">New Child Page</th>
    <th width="30%">Actions</th>
  </thead>
  <%= nested_pages @pages.arrange(:order => :position) %>
  <tr>
    <td colspan=5>
      <%= link_to 'New Page', new_admin_page_path, :class => 'button is-add is-warning large-button' %>
    </td>
  </tr>
</table>

app/views/admin/pages/new.html.erb
<h1 class="title">New Page <%= link_to 'Back to All Page', admin_pages_path, :class => 'button is-blue is-back is-pulled-right large-button' %></h1>

<%= render 'label_modal' %>

<%= form_for [:admin, @page] do |form| %>
  <%= render "form", form: form %>
<% end %>

app/views/layouts/_adminnavbar.html.erb
<aside class="admin menu is-fullheight is-desktop">

  <div class="brand">
  Administration Menu
  <div class="navbar-burger burger" data-target="adminMenu" id="admin-toggle">
    <span></span>
    <span></span>
    <span></span>
  </div>
  </div>
  <div id="adminMenu" class="admin-menu">
    <p class="menu-label">
      General Administration
    </p>

    <ul class="menu-list">
      <li><%= link_to 'Dashboard', admin_path, class: "#{cp(admin_path)} dashboard" %></li>
    </ul>
    <p class="menu-label">
      Content Administration
    </p>
    <ul class="menu-list">
      <li><%= link_to 'Survey Templates', admin_survey_templates_path, class: "#{cp(admin_survey_templates_path)} surveys"  %></li>
      <li><%= link_to 'Labels', admin_labels_path, class: "#{cp(admin_labels_path)} labels" %></li>
      <li><%= link_to 'Pages', admin_pages_path, class: "#{cp(admin_pages_path)} pages" %></li>

    </ul>
    <p class="menu-label">
      Site Administration
    </p>
    <ul class="menu-list">
      <li><%= link_to 'Supporting Units', admin_supporting_units_path, class: "#{cp(admin_supporting_units_path)} supporting-units" %></li>
      <li><%= link_to 'User Management', admin_users_path, class: "#{cp(admin_users_path)} users" %></li>
      <li><%= link_to 'Site Information', admin_site_informations_path, class: "#{cp(admin_site_informations_path)} information" %></li>
    </ul>
  </div>
</aside>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="columns is-desktop">
      <div class="column is-hidden-desktop supporting-units is-hidden-print">
        <h3>Supporting Units</h3>
        <% Admin::SupportingUnit.where("url != ''").all.each do |unit| %>
            <a href="<%= unit.url %>" target="_blank">
              <%= unit.unit %>
            </a>
        <% end %>
      </div>
      <div class="column is-6 about">
        <% @about_site = Admin::SiteInformation.where("name = 'about_site'").first %>
        <h3><%= @about_site.header %></h3>
        <%= sanitize @about_site.text.html_safe() %>
      </div>
      <div class="column is-6 contact">
        <% @contact_info = Admin::SiteInformation.where("name = 'contact_info'").first %>
        <h3><%= @contact_info.header %></h3>
        <%= sanitize @contact_info.text.html_safe() %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_internalNavbar.html.erb
<nav class="navbar internal">
  <div class="navbar-brand">
    <!-- <a class="navbar-item" >
      Online Investigators Guides Administration
    </a> -->
    Researcher Handbook

    <div class="navbar-burger burger" data-target="navMenuTransparent">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navMenuTransparent" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">

        <%= link_to "Shibb_Relative", auth_scheme %>
        <div class="field is-grouped">
          <% if current_user %>
          <p class="control">
            <%= link_to session_path(current_user), method: "delete", :class => 'bd-tw-button button' do %>
              <span class="icon">
                <i class="fa fa-unlock"></i>
              </span>
              <span>
                Log Out
              </span>
            <% end %>
          </p>
          <% else %>
            <p class="control">
              <%= link_to 'login', controller: 'sessions', action: 'new', :class => 'bd-tw-button button' do %>
                <span class="icon">
                  <i class="fa fa-lock"></i>
                </span>
                <span>
                  Log Insdsfsfsdfsdf
                </span>
              <% end %>
              <!-- <a class="bd-tw-button button" data-social-network="Twitter" data-social-action="tweet" data-social-target="https://bulma.io" target="_blank" href="https://twitter.com/intent/tweet?text=Bulma: a modern CSS framework based on Flexbox&amp;hashtags=bulmaio&amp;url=https://bulma.io&amp;via=jgthms">
                <span class="icon">
                  <i class="fa fa-lock"></i>
                </span>
                <span>
                  Login In
                </span>
              </a> -->
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_login.html.erb
<% if Rails.env.local? %>
  <div class="navbar-item">
    <% if not current_user %>
      <p class="control">
        <%= link_to "Login", root_url + "login", :class => 'bd-tw-button button login large-button', :target => '_self' %>
      </p>
    <% end %>
  </div>
<% else %>
  <div class="navbar-item">
    <% if not current_user %>
      <p class="control">
        <%= link_to "Login", root_url + "auth/saml", :class => 'bd-tw-button button login large-button', :target => '_self' %>
      </p>
    <% end %>
  </div>
<% end %>
<% if current_user %>
<div class="navbar-item has-dropdown is-hoverable">
  <a class="navbar-link  is-active" href="">
    Welcome, <%= current_user.first_name %>
  </a>
  <div class="navbar-dropdown ">
    <% current_user.surveys.each do |view| %>
      <%= link_to view.name, root_path(:user => current_user.id, :view => view.id), :class => 'navbar-item' %>
    <% end %>
    <%= link_to 'Manage my Views', user_surveys_path(current_user), :class => 'navbar-item' %>

    <% if current_user.is_admin? %>
      <hr class="navbar-divider">
      <%= link_to 'Admin Portal', admin_path, :class => 'navbar-item' %>
    <% end %>
    <hr class="navbar-divider">
    <% if Rails.env.local? %>
      <%= link_to session_path(current_user), method: "delete", :class => 'navbar-item is-active', :target => '_self' do %>
        <span>
          Log Out
        </span>
      <% end %>
    <% else %>
      <%= link_to single_logout_omniauth_callbacks_path(:slo => '1'), :class => 'navbar-item is-active', :target => '_self' do %>
        <span>
          Log Out
        </span>
      <% end %>
    <% end %>
  </div>
</div>
<% end %>

app/views/layouts/_maintenance_mode.html.erb
<div class="maintenance_mode notification is-warning">
<h2> <%= @maintenance_mode.header %> </h2>
<%= sanitize @maintenance_mode.text.html_safe() %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <div class="print-logo">
    <%= image_tag("print-logo.jpg") %>
  </div>
  <div class="navbar-brand logo">
    <%= image_tag("emory-shield-white.png") %>
    <div class="navbar-start site-branding is-hidden-desktop">
      <div class="eu-brand">Emory University</div>
      <div class="site-information">
        <%= sanitize Admin::SiteInformation.where("name = 'branding'").first.text.html_safe() %>
      </div>
    </div>

  </div>

  <div class="navbars" id="navMenu">
    <div class="primary-navbar">
      <div class="navbar-menu">
        <div class="navbar-start site-branding is-hidden-mobile">
          <div class="eu-brand">Emory University</div>
          <div class="site-information">
            <%= sanitize Admin::SiteInformation.where("name = 'branding'").first.text.html_safe() %>
          </div>
        </div>

        <div class="navbar-end">
          <div class="navbar-item supporting-units is-hidden-touch">
            <span class="unit-label">Supporting Units</span>
          <% Admin::SupportingUnit.where("url != ''").all.each do |unit| %>
              <a class="navbar-item" href="<%= unit.url %>" target="_blank">
                <%= unit.unit %>
              </a>
          <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="secondary-navbar">

        <div class="navbar-start">
          <a class="navbar-item" href="/">
            Table of Contents
          </a>
          <div class="navbar-menu is-hidden-touch">
            <div class="navbar-end">
              <div class="navbar-item">
                <%= render "layouts/search" %>
              </div>
              <%= render 'layouts/login' %>
            </div>
          </div>
        </div>
        <div class="navbar-burger burger" data-target="navMenu" id="nav-toggle">
          <span></span>
          <span></span>
          <span></span>
        </div>
    </div>
    <div class="navbar-menu is-hidden-desktop is-hidden-print">
            <%= render "layouts/search" %>
            <%= render 'layouts/login' %>
    </div>
  </div>
</nav>

app/views/layouts/_search.html.erb
<%= form_tag(search_path, :method => "get", :target => "_self") do %>
  <div class="field has-addons">
    <div class="control">
      <%= text_field_tag :search, params[:search], placeholder: "Search Pages" %>
    </div>
    <div class="control">
      <%= button_tag(type: "submit", class: "button is-info") do %>
        <span class="fa fa-search"></span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %> Admin Portal </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="adminSite">
    <% if @maintenance_mode.isOn %>
      <div class="admin_maintenance_notification">
        Site is in Maintenance Mode.  <%= link_to 'Turn off maintenance mode.', admin_site_information_toggle_maintenance_mode_path(@maintenance_mode.id) %>
      </div>
    <% end %>
    <% if current_user.is_admin? %>
      <%= render 'layouts/navbar'%>
      <div class="columns is-gapless is-desktop admin">
        <div class="column is-one-quarter-desktop is-hidden-touch no-bottom-padding">
          <%= render 'layouts/adminnavbar' %>
        </div>
        <div class="column is-hidden-desktop no-bottom-padding">
          <%= render 'layouts/adminnavbar' %>
        </div>
        <div class="column">
        <%= yield %>
        </div>
      </div>
    <% else %>
      <script type="text/javascript">
        window.location.href="/"
      </script>
    <% end %>
  </body>
</html>

app/views/pages/_feedbackSurvey.html.erb
<a href="https://www.surveymonkey.com/r/7FG6PP5" target="_blank" class="button feedback is-info is-hidden-mobile"><span class="fa fa-commenting-o"></span>Give us Feedback</a>

app/views/pages/_page.html.erb
<tr>
  <td class='nested<%= page.ancestry_depth %>' >
    <%= page.title %>
  </td>
  <td>
    <%= page.updated_at.strftime('%m/%d/%y')   %>
  </td>
  <td>
    <div class="position"><%= page.position %></div>
    <div class="controls">
      <% if page.position != 1 %>
        <%= link_to "", {:controller => "pages", :action => "move", :method => "move_higher", :page_id => page.id }, :class => 'control up'%>
      <% end %>
      <% if page.position != page.siblings.count %>
        <%= link_to "", {:controller => "pages", :action => "move", :method => "move_lower", :page_id => page.id }, :class => 'control down'%>
      <% end %>
    </div>
  </td>
  <td>
    <%= link_to '', new_page_path(:parent_id => page), :class => 'button is-warning is-add', rel: 'tooltip' %>
    <%= link_to '', page, :class => 'button is-show is-primary' %>
    <%= link_to '', edit_page_path(page), :class => 'button is-edit is-gray'  %>
    <%= link_to '', page, method: :delete, data: { confirm: 'If any children pages exist, they will also be removed. Are you sure you want to delete this page? ' }, :class => 'button is-delete is-red'  %>
  </td>


</tr>

app/views/pages/_unfilteredSideMenu.html.erb
<%= link_to 'Table of Contents', root_path, class: "#{cp(root_path)} table-of-contents" %>
  <ul class="menu-list">
    <% Page.roots.order(position: :asc).each do |p| %>
        <li class="parent <% if current_page?(p) %> is-active is-active-parent<% end %>">
          <%= link_to h(p.title), p %>
          <!-- REMOVED TO HIDE SUBMENU CHILDREN -->
          <!-- <% if p.children.present? %>
            <%= render 'sideMenuSub', p: p %>
          <% end %> -->
        </li>
    <% end %>
  </ul>

app/views/pages/edit.html.erb
<h1 class="title">Editing Page <%= link_to 'Back to All Page', pages_path, :class => 'button is-blue is-back is-pulled-right' %></h1>

<%= render 'form', page: @page %>

<!-- <%= link_to 'Show', @page %> | -->
<!-- <%= link_to 'Back', pages_path, :class => 'button is-gray is-back' %> -->

app/views/pages/index.html.erb
<%= render partial: "sideMenu" %>

<div class="column table-of-contents">
  <% if params[:user] and params[:view] %>
    <% if not current_user.id.to_s == params[:user] %>
      <div class="notification is-danger">You do not have authorization for this customized view. To create your own customized view, <%= link_to 'click here', user_surveys_path(current_user.id) %></div>
      <%= render :partial => 'unfilteredView' %>
    <% else %>
      <%= render :partial => 'filteredView' %>
    <% end %>
  <% else %>
    <%= render :partial => 'unfilteredView' %>  
  <% end %>

</div>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>
t
<%= render partial: "sideMenu" %>
  <section class="column page-body">

    <% if params[:user] and params[:view] %>
      <% if not current_user.id.to_s == params[:user] %>
        <div class="notification is-danger">You do not have authorization for this customized view. To create your own customized view, <%= link_to 'click here', user_surveys_path(current_user.id) %></div>
      <% end %>
    <% end %>

    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <% @page.ancestors.each do |page| %>
          <li>
            <% if params[:user] and params[:view] and not current_user.id.to_s == params[:user] %>
              <%= link_to page.title, page_path(page, :user => params[:user], :view => params[:view]) %>
            <% else %>
              <%= link_to page.title, page_path(page) %>
            <% end %>
          </li>
        <% end %>
        <li class="is-active"><%= link_to @page.title, @page, 'aria-current'=>'page' %></li>
      </ul>
      <a class="button print" onclick="printWindow();" ><span class="fa fa-print"></span>Print Page</a>
    </nav>

    <h1 class="title">
      <%= @page.header %>
    </h1>
    <div class="page-body">
      <%= sanitize raw @page.body %>

    <!--  IF PAGE IS ROOT, BUILD ONLY DIRECT DESCENDANTS -->
    <% if @page.is_root? %>
      <ol type="a">
        <% if params[:user] and params[:view] and current_user %>
          <% if current_user.id.to_s == params[:user] %>
            <% @page.descendants(:to_depth => 1).each do |child| %>
              <% if @allContentPages.include? child.id or @allAncestors.include? child.id %>
                <li>
                  <%= link_to child.title, page_path(child, :user => params[:user], :view => params[:view]) %>
                </li>
              <% end %>
            <% end %>
          <% else %>
            <% @page.descendants(:to_depth => 1).each do |child| %>
              <li><%= link_to child.title, child %></li>
            <% end %>
          <% end %>
        <% end %>
      </ol>
    <!--  ELSE DISPLAY ALL DIRECT DESCENDANTS -->
    <% else %>
      <!-- BUILD ANCHOR MENU -->
      <% if params[:user] and params[:view] and current_user and @page.has_children? %>
        <ol class="anchor-menu">
          <% @page.descendants.at_depth(2).each do |child| %>
            <% if @allContentPages.include? child.id or @allAncestors.include? child.id %>
              <li>
                <%= link_to child.title, "#"+child.title.parameterize %>
              </li>
            <% end %>
          <% end %>
        </ol>
      <% elsif @page.has_children? %>
        <ol class="anchor-menu">
          <% @page.descendants.at_depth(2).each do |child| %>
            <li>
              <%= link_to child.title, "#"+child.title.parameterize %>
            </li>
          <% end %>
        </ol>
      <% end %>

      <!-- TRAVERSE DESCENDANTS AND CREATE PAGE -->
      <% if params[:user] and params[:view] and current_user and @page.has_children? %>
      <ol>
          <% @page.descendants.at_depth(2).each_with_index do |child, index| %>
            <% if @allContentPages.include? child.id or @allAncestors.include? child.id %>
              <li>
                <article>
                  <a id="<%= child.title.parameterize %>">
                    <h2 class="subtitle"><%= child.header %></h2>
                  </a>
                  <%= sanitize raw child.body %>
                  <% if child.has_children? %>
                    <ol type="a" class="children">
                    <% child.descendants.each_with_index do | subChild, subIndex | %>
                      <li>
                        <article>
                          <h2 class="subtitle"><%= subChild.header %></h2>
                          <%= raw subChild.body %>
                        </article>
                      </li>
                    <% end %>
                    </ol>
                  <% end %>
                </article>
              </li>
            <% end %>
          <% end %>
      </ol>
      <% elsif @page.has_children? %>
        <% @page.descendants.at_depth(2).each_with_index do |child, index| %>
          <article>
            <a id="<%= child.title.parameterize %>">
              <h2 class="subtitle"><%= index + 1%>. <%= child.header %></h2>
            </a>
            <%= sanitize raw child.body %>
            <% if child.has_children? %>
              <% child.descendants.at_depth(child.ancestry_depth + 1).each_with_index do | subChild, subIndex | %>
                <article>
                  <h2 class="subtitle"><%= index + 1%>.<%= subIndex + 1 %>. <%= subChild.header %></h2>
                  <%= raw subChild.body %>
                  <% if subChild.has_children? %>
                    <% subChild.descendants.at_depth(subChild.ancestry_depth + 1).each_with_index do | subChild2, subIndex2 | %>
                      <article>
                        <h2 class="subtitle"><%= index + 1%>.<%= subIndex + 1 %>.<%= subIndex2 + 1 %>. <%= subChild2.header %></h2>
                        <%= raw subChild2.body %>
                      </article>
                    <% end %>
                  <% end %>
                </article>

              <% end %>
            <% end %>
          </article>
        <% end %>
      <% end %>
    <% end %>
    </div>
  </section>