config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :site_informations
  end
  namespace :admin do
    resources :supporting_units
  end
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  namespace :admin do
    resources :pages do
        get :move
    end
    resources :pages
    resources :survey_templates do
      get :toggle_default
    end
    resources :labels
    resources :users do
      get :toggle_admin
    end
    get '', to: 'dashboard#index', as: '/'
    resource :broken_link do
      get :runReport
    end
    resources :site_informations do
      get :toggle_maintenance_mode
    end
  end

  resources :sessions
  resources :omniauth_callbacks, only: :index do
    collection do
      get :single_logout
    end
  end

  resources :pages, :except => ['edit', 'new', 'update', 'destroy']
  resources :users do
    resources :surveys, :path => 'views' do
      get :toggle_default
    end
  end
  get 'sitemap', to:'pages#sitemap', as: 'sitemap'
  match  '/auth/:provider/callback', :to => 'omniauth_callbacks#saml', via: [:get, :post]
  match  'pages/auth/:provider/callback', :to => 'omniauth_callbacks#saml', via: [:get, :post]
  root 'pages#index'
  get '/search' => 'pages#search'
end

app/models/label.rb
class Label < ApplicationRecord
  # has_and_belongs_to_many :pages, dependent: :destroy
  has_many :answers_label, :class_name => 'AnswersLabel'
  has_many :answers, through: :answers_label

  validates_uniqueness_of :name, :message => '%{value} has already been taken'
end

app/models/page.rb
class Page < ApplicationRecord
  has_ancestry :cache_depth => true
  acts_as_list scope: [:ancestry]
  has_and_belongs_to_many :labels

  def self.search(search)
    where("header LIKE ? OR title LIKE ? OR body LIKE ?", "%#{search}%", "%#{search}%" ,"%#{search}%")
  end

end

app/controllers/admin/labels_controller.rb
class Admin::LabelsController < Admin::BaseController
  before_action :set_label, only: [:show, :edit, :update, :destroy]

  # GET /labels
  # GET /labels.json
  def index
    @labels = Label.all
  end

  # GET /labels/1
  # GET /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new

  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels
  # POST /labels.json
  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        format.html { redirect_to action: "index", notice: 'Label was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new }
        format.js
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1
  # PATCH/PUT /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to action: "index", notice: 'Label was successfully updated.' }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1
  # DELETE /labels/1.json
  def destroy
    @label.destroy
    respond_to do |format|
      format.html { redirect_to action: "index", notice: 'Label was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def label_params
      params.require(:label).permit(:name)
    end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:show, :edit, :update, :destroy]

  # GET /labels
  # GET /labels.json
  def index
    @labels = Label.all
  end

  # GET /labels/1
  # GET /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels
  # POST /labels.json
  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        format.html { redirect_to @label, notice: 'Label was successfully created.' }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1
  # PATCH/PUT /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to @label, notice: 'Label was successfully updated.' }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1
  # DELETE /labels/1.json
  def destroy
    @label.destroy
    respond_to do |format|
      format.html { redirect_to labels_url, notice: 'Label was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def label_params
      params.require(:label).permit(:name)
    end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/admin/labels/_form.html.erb
  <% if @label.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="error_explanation" style="display: none;">
    <ul>
      <li></li>
    </ul>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :label_name, :class => 'label-input' %>
  </div>

  <div class="actions">
    <a class="button is-primary is-save">
      <%= form.submit 'Save Label', :class => 'remove-label-modal button is-transparent' %>
    </a>
  </div>

app/views/admin/labels/create.js.erb
<% if @label.errors.any? %>
  $('#error_explanation').attr('style', 'display');
  $('#error_explanation ul li').html("<%= j @label.errors.full_messages.join('; ') %>");
<% else %>
  var $label = $("<label>").attr("for", "page_label_ids_"+<%= @label.id.to_s %>).text("<%= @label.name.to_s %>");
  var $input = $('<input type="checkbox">').attr({value: <%= @label.id.to_s %>, name: "page[label_ids][]", id: "page_label_ids_"+<%= @label.id.to_s %>});
  var $div = $('<div/>').addClass("collection-check-box").append($label).append($input);

  $('#label-list').append($div);

  if ( $input.is(':checked')) {
    $(input).closest('.collection-check-box').addClass('selected');
  }

  $input.change(function() {
    if ($(this).prop('checked')) {
      $(this).closest('.collection-check-box').toggleClass('selected');
    } else {
      $(this).closest('.collection-check-box').toggleClass('selected');
    }
  });

  $("#add-label").removeClass('is-active');
<% end %>

app/views/admin/labels/edit.html.erb
<h1 class="title">Editing Label <%= link_to 'Back to All Labels', admin_labels_path, :class => 'button is-blue is-back is-pulled-right large-button' %></h1>

<%= form_for @label, url: admin_label_path(@label) do |form| %>
  <%= render 'form', :form => form %>
<% end %>

app/views/admin/labels/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Labels<%= link_to 'New Label', new_admin_label_path, :class => 'button is-add is-warning large-button is-pulled-right' %></h1>

<table class="table is-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td data-label="Label Name"><%= label.name %></td>
        <td><%= link_to 'Edit', edit_admin_label_path(label), :class => 'button is-gray is-edit large-button' %>
          <%= link_to 'Delete', admin_label_path(label), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'button is-red is-delete large-button'  %></td>
      </tr>
    <% end %>
    <tr>
      <td colspan=2>
        <%= link_to 'New Label', new_admin_label_path, :class => 'button is-warning is-add large-button' %>
      </td>
    </tr>
  </tbody>
</table>

<br>

app/views/admin/labels/new.html.erb
<h1 class="title">New Label <%= link_to 'Back to All Labels', admin_labels_path, :class => 'button is-blue is-back is-pulled-right large-button' %></h1>

<%= form_for [:admin, @label] do |form| %>
  <%= render "form", :form => form %>
<% end %>

app/views/admin/labels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @label.name %>
</p>

<%= link_to 'Edit', edit_admin_label_path(@label) %> |
<%= link_to 'Back', admin_labels_path %>