config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :site_informations
  end
  namespace :admin do
    resources :supporting_units
  end
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  namespace :admin do
    resources :pages do
        get :move
    end
    resources :pages
    resources :survey_templates do
      get :toggle_default
    end
    resources :labels
    resources :users do
      get :toggle_admin
    end
    get '', to: 'dashboard#index', as: '/'
    resource :broken_link do
      get :runReport
    end
    resources :site_informations do
      get :toggle_maintenance_mode
    end
  end

  resources :sessions
  resources :omniauth_callbacks, only: :index do
    collection do
      get :single_logout
    end
  end

  resources :pages, :except => ['edit', 'new', 'update', 'destroy']
  resources :users do
    resources :surveys, :path => 'views' do
      get :toggle_default
    end
  end
  get 'sitemap', to:'pages#sitemap', as: 'sitemap'
  match  '/auth/:provider/callback', :to => 'omniauth_callbacks#saml', via: [:get, :post]
  match  'pages/auth/:provider/callback', :to => 'omniauth_callbacks#saml', via: [:get, :post]
  root 'pages#index'
  get '/search' => 'pages#search'
end

app/models/survey.rb
class Survey < ApplicationRecord
  # the name is mandatory
  validates_presence_of :name

  belongs_to :user
  belongs_to :survey_template
  has_and_belongs_to_many :answers
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :get_user
  before_action :get_survey_template
  before_action :set_survey, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  before_action :maintenance_mode

  def toggle_default
    Survey.where("user_id = ?", params[:user_id]).update_all(:is_default => false)
    Survey.where("id = ? AND user_id = ?", params[:survey_id], params[:user_id]).update(:is_default => true)
    redirect_to user_surveys_path(:user_id => current_user.id)
  end

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = @user.surveys
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey  = @user.surveys.build
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = @user.surveys.build(survey_params)

    respond_to do |format|
      if @survey.save
        # If the Survey that we are saving is the defualt,
        # then we need to change the others Survey not to be the default.
        if @survey.is_default
          Survey.where("id != ? AND user_id = ?", @survey.id, @survey.user_id).update_all(:is_default => false)
        end

        format.html { redirect_to user_surveys_url(@user), notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      # If THIS survey is the default and the user is trying to change it,
      # we can not allow this operation.
      if @survey.is_default && survey_params[:is_default] == "0"
        redirect_to edit_user_survey_path(@user, @survey),
          :notice=> 'There must be one default view at all times.' and return
      end

      if @survey.update(survey_params)
        # If we are going to update THIS view as the default,
        # then we need to set the others Surveys is_default column to false.
        if @survey.is_default
          Survey.where("id != ? AND user_id = ?", @survey.id, @survey.user_id).update_all(:is_default => false)
        end

        format.html { redirect_to user_surveys_url(@user), notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to user_surveys_path(@user), notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # get_user converts the user_id given by the routing
    # into an @user object, for use here and in the view
    def get_user
      @user = User.find(params[:user_id])
    end

    def get_survey_template
      # TODO: Need to figure out how to handle if there is no default survey template.
      @survey_template = SurveyTemplate.where(["is_default = ?", true]).first
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = @user.surveys.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:name, :description, :is_default, :user_id, :survey_template_id, answer_ids:[])
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_with(model: [@user, survey], local: true, :html => {:target=>'_self'}) do |form| %>
  <% if survey.errors.any? %>
    <div id="error_explanation" class="notification is-danger">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p id="notice"><%= notice %></p>

  <%= form.hidden_field :user_id, value: @user.id %>
  <%= form.hidden_field :survey_template_id, value: @survey_template.id %>

  <div class="field">
    <%= form.label 'Name of View' %>
    <%= form.text_field :name, id: :survey_name %>
  </div>

  <div class="field">
    <div class="checkbox">
      <%= form.label :is_default, "Default View" %>
      <%= form.check_box :is_default, id: :survey_is_default %>
    </div>
  </div>

  <div class="field">
    <%= form.label 'Description of View' %>
    <%= form.text_area :description, id: :survey_description, :class => 'textarea' %>
  </div>

  <ol class="questions">
    <% @survey_template.questions.each do |question| %>
    <li>
      <%= question.content %>
      <ol class="answers">
        <% if QuestionType.find(question.question_type_id).name == 'checkbox' %>
          <div class="field">
            <%= form.collection_check_boxes :answer_ids, question.answers, :id, :content do |b| %>
              <div class="checkbox">
                <%= b.check_box %>
                <%= b.label %>
              </div>
              <br/>
            <% end %>
          </div>
        <% else %>
          <div class="field">
            <div class = "radio" >
              <%= form.collection_check_boxes :answer_ids, question.answers, :id, :content do |b| %>
                <div class="checkbox">
                  <%= b.check_box %>
                  <%= b.label %>
                </div>
                <br/>
              <% end %>
            </div>
            </div>
        <% end %>
      </ol>
    </li>
    <% end %>
  </ol>

  <div class="actions">
    <a class="button is-primary is-save">
      <%= form.submit 'Save View', :class => 'button is-primary large-button' %>
    </a>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<div class="column">
  <h1 class="title">Editing View<%= link_to 'Back to My Views', user_surveys_path(@user), :class => 'button is-blue is-back is-pulled-right large-button' %></h1>

  <section>
    <%= render 'form', survey: @survey %>
  </section>

</div>

<!-- <%= link_to 'Show', [@user, @survey] %> | -->

app/views/surveys/index.html.erb
<div class="column">
  <% if notice %>
  <p id="notice"  class="notification"><%= notice %></p>
  <% end %>
  <h1 class="title">Views for <%= @user.name %></h1>
  <% if !@surveys.empty? %>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th width="10%">Default</th>
          <th width="40%">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @surveys.each do |survey| %>
          <tr>
            <td data-label="Name"><%= survey.name %></td>
            <td data-label="Description"><%= survey.description %></td>
            <td data-label="Default"><% if survey.is_default %><span class="fa fa-check"></span><% else %> <span class="fa fa-times"></span><% end %></td>
            <td class="stacked-button">
              <% if survey.is_default %>
                <%= link_to 'Set As Default', user_survey_toggle_default_path(:user_id => current_user.id, :survey_id => survey.id), :class => 'button is-default large-button', :disabled => true %>
              <% else %>
                <%= link_to 'Set As Default', user_survey_toggle_default_path(:user_id => current_user.id, :survey_id => survey.id), :class => 'button is-default large-button' %>
              <% end %>
              <%= link_to 'View', root_path(:user => current_user.id, :view => survey.id), :class => 'button show is-primary is-show large-button', target: '_self' %>
              <%= link_to 'Edit', edit_user_survey_path( @user, survey ) , :class => 'button edit is-gray is-edit large-button', target: '_self' %>
              <%= link_to 'Delete', [ @user, survey], method: :delete, data: { confirm: 'Are you sure?' }, :class => 'button is-red is-delete large-button', target: '_self' %>

            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>
      No surveys have been created yet.
    </p>
  <% end %>

  <br>

  <%= link_to 'Create New View', new_user_survey_path(@user), :class => 'button is-warning is-add large-button'  %>
</div>

app/views/surveys/new.html.erb
<div class="column">
<h1 class="title">Create New View <%= link_to 'Back to My Views', user_surveys_path, :class => 'button is-blue is-back is-pulled-right large-button' %></h1>

<section>
  <%= render 'form', survey: @survey %>
</section>
</div>

app/views/surveys/show.html.erb
<div class="column">
  <% if notice %>
  <p id="notice"  class="notification"><%= notice %></p>
  <% end %>

<p>
  <strong>Current View:</strong>
  <%= @survey.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @survey.description %>
</p>

<ol class="questions">
  <% @survey_template.questions.each do |question| %>
  <li>
    <%= question.content %>
    <ol class="answers">
      <% if QuestionType.find(question.question_type_id).name == 'checkbox' %>
          <%= collection_check_boxes :survey, :answer_ids, question.answers, :id, :content, { disabled: -> (content) {true}} do |b| %>
            <div class="checkbox">
              <%= b.check_box %>
              <%= b.label %>
            </div>
            <br/>
          <% end %>
      <% else %>
          <%= collection_check_boxes :survey, :answer_ids, question.answers, :id, :content, { disabled: -> (content) {true}} do |b| %>
            <div class="checkbox">
              <%= b.check_box %>
              <%= b.label %>
            </div>
            <br/>
        <% end %>
      <% end %>
      <% AnswersSurvey.where("survey_id = ?", @survey.id).each do |answer| %>
        <% AnswersLabel.where(:answer_id => answer.answer_id).each do |label| %>
          <% LabelsPage.where(:label_id => label.label_id).each do |page| %>
          <%= link_to 'Page', page_path(page.page_id, :user => @user, :view => @survey.id) %>
            <%= Page.where(:id => page.page_id) %>
            <%= page.page_id %>
          <% end %>
        <% end %>
      <% end %>
      <!-- <% Answer.where("question_id = ?", question.id).each do |answer| %>
       <%= answer.id %>
       <% AnswersLabel.where(:answer_id => answer.id).each do |label| %>
         <% Label.where(:id => label.label_id).each do |l| %>
           <%= l.name %>
         <% end %>
          <%= label.label_id %>
       <% end %>
      <% end %> -->
    </ol>
  </li>
  <% end %>
</ol>

</div>