config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :site_informations
  end
  namespace :admin do
    resources :supporting_units
  end
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  namespace :admin do
    resources :pages do
        get :move
    end
    resources :pages
    resources :survey_templates do
      get :toggle_default
    end
    resources :labels
    resources :users do
      get :toggle_admin
    end
    get '', to: 'dashboard#index', as: '/'
    resource :broken_link do
      get :runReport
    end
    resources :site_informations do
      get :toggle_maintenance_mode
    end
  end

  resources :sessions
  resources :omniauth_callbacks, only: :index do
    collection do
      get :single_logout
    end
  end

  resources :pages, :except => ['edit', 'new', 'update', 'destroy']
  resources :users do
    resources :surveys, :path => 'views' do
      get :toggle_default
    end
  end
  get 'sitemap', to:'pages#sitemap', as: 'sitemap'
  match  '/auth/:provider/callback', :to => 'omniauth_callbacks#saml', via: [:get, :post]
  match  'pages/auth/:provider/callback', :to => 'omniauth_callbacks#saml', via: [:get, :post]
  root 'pages#index'
  get '/search' => 'pages#search'
end

app/models/page.rb
class Page < ApplicationRecord
  has_ancestry :cache_depth => true
  acts_as_list scope: [:ancestry]
  has_and_belongs_to_many :labels

  def self.search(search)
    where("header LIKE ? OR title LIKE ? OR body LIKE ?", "%#{search}%", "%#{search}%" ,"%#{search}%")
  end

end

app/models/survey_template.rb
class SurveyTemplate < ApplicationRecord
  # the name is mandatory
  validates_presence_of :name
  validates_presence_of :questions

  has_many :questions, dependent: :destroy
  has_many :surveys

  has_many :answers_label

  accepts_nested_attributes_for :questions, allow_destroy: true
end

app/controllers/admin/survey_templates_controller.rb
class Admin::SurveyTemplatesController < Admin::BaseController
  before_action :set_survey_template, only: [:show, :edit, :update, :destroy]
  # before_action :is_admin?, only: [:index, :show, :new, :edit, :create, :update, :destroy]

  def toggle_default
    SurveyTemplate.where(id: params[:survey_template_id]).update(:is_default => true)
    SurveyTemplate.where.not(id: params[:survey_template_id]).update_all(:is_default => false)
    redirect_to admin_survey_templates_path
  end

  # GET /survey_templates
  # GET /survey_templates.json
  def index
    @survey_templates = SurveyTemplate.all
  end

  # GET /survey_templates/1
  # GET /survey_templates/1.json
  def show
  end

  # GET /survey_templates/new
  def new
    @survey_template = SurveyTemplate.new
  end

  # GET /survey_templates/1/edit
  def edit
  end

  # POST /survey_templates
  # POST /survey_templates.json
  def create
    @survey_template = SurveyTemplate.new(survey_template_params)

    respond_to do |format|
      if @survey_template.save
        # If the Survey Template that we are saving is the defualt,
        # then we need to change the others Survey Templates not to be the default.
        if @survey_template.is_default
          SurveyTemplate.where.not(id: @survey_template.id).update_all(:is_default => false)
        end

        format.html { redirect_to action: "index", notice: 'Survey template was successfully created.' }
        format.json { render :show, status: :created, location: @survey_template }
      else
        format.html { render :new }
        format.json { render json: @survey_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /survey_templates/1
  # PATCH/PUT /survey_templates/1.json
  def update
    respond_to do |format|
      # If THIS template is the default and the user is trying to change it,
      # we can not allow this operation.
      if @survey_template.is_default && survey_template_params[:is_default] == "0"
        redirect_to edit_admin_survey_template_path(@survey_template),
          :notice=> 'There must be one default template at all times.' and return
      end

      if @survey_template.update(survey_template_params)
        # If we are going to update THIS template as the default,
        # then we need to set the others Survey Templates is_default column to false.
        if @survey_template.is_default
          SurveyTemplate.where.not(id: @survey_template.id).update_all(:is_default => false)
        end

        format.html { redirect_to action: "update", notice: 'Survey template was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey_template }
      else
        format.html { render :edit }
        format.json { render json: @survey_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survey_templates/1
  # DELETE /survey_templates/1.json
  def destroy
    if @survey_template.is_default
      redirect_to admin_survey_templates_path,
        :notice=> 'There must be one default template at all times.' and return
    end
    
    @survey_template.destroy
    respond_to do |format|
      format.html { redirect_to action: "index", notice: 'Survey template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey_template
      @survey_template = SurveyTemplate.find(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_survey_template
      @survey_template = SurveyTemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_template_params
      params.require(:survey_template).permit(:name, :is_default,
        questions_attributes: [:_destroy, :id, :survey_template_id, :content, :question_type_id,
          answers_attributes: [:_destroy, :id, :question_id, :content, label_ids: []]])
    end
end

app/controllers/survey_templates_controller.rb
class SurveyTemplatesController < ApplicationController
  before_action :set_survey_template, only: [:show, :edit, :update, :destroy]
  before_action :is_admin?, only: [:index, :show, :new, :edit, :create, :update, :destroy]

  # GET /survey_templates
  # GET /survey_templates.json
  def index
    @survey_templates = SurveyTemplate.all
  end

  # GET /survey_templates/1
  # GET /survey_templates/1.json
  def show
  end

  # GET /survey_templates/new
  def new
    @survey_template = SurveyTemplate.new
  end

  # GET /survey_templates/1/edit
  def edit
  end

  # POST /survey_templates
  # POST /survey_templates.json
  def create
    @survey_template = SurveyTemplate.new(survey_template_params)

    respond_to do |format|
      if @survey_template.save
        # If the Survey Template that we are saving is the defualt,
        # then we need to change the others Survey Templates not to be the default.
        if @survey_template.is_default
          SurveyTemplate.where.not(id: @survey_template.id).update_all(:is_default => false)
        end

        format.html { redirect_to @survey_template, notice: 'Survey template was successfully created.' }
        format.json { render :show, status: :created, location: @survey_template }
      else
        format.html { render :new }
        format.json { render json: @survey_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /survey_templates/1
  # PATCH/PUT /survey_templates/1.json
  def update
    respond_to do |format|
      if @survey_template.update(survey_template_params)
        # If the Survey Template that we are editing is the defualt,
        # then we need to change the others Survey Templates not to be the default.
        if @survey_template.is_default
          SurveyTemplate.where.not(id: @survey_template.id).update_all(:is_default => false)
        end

        format.html { redirect_to @survey_template, notice: 'Survey template was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey_template }
      else
        format.html { render :edit }
        format.json { render json: @survey_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survey_templates/1
  # DELETE /survey_templates/1.json
  def destroy
    @survey_template.destroy
    respond_to do |format|
      format.html { redirect_to survey_templates_url, notice: 'Survey template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey_template
      @survey_template = SurveyTemplate.find(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_survey_template
      @survey_template = SurveyTemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_template_params
      params.require(:survey_template).permit(:name, :is_default,
        questions_attributes: [:id, :survey_template_id, :content, :question_type_id, :_destroy,
          answers_attributes: [:id, :question_id, :content, :_destroy]])
    end
end

app/helpers/survey_templates_helper.rb
module SurveyTemplatesHelper
end

app/views/admin/survey_templates/_answer_fields.html.erb
<fieldset>
  <%= form.hidden_field :_destroy %>
  <%= link_to " ", '#', class: "remove_fields fa fa-times-circle" %>
  <%= form.label :content, "Answer" %>
  <%= form.text_field :content %>
  
  <%= form.label "Labels to Show:", :class => 'label adjusted-top' %>

  <%= form.collection_check_boxes :label_ids, Label.all, :id, :name do |b| %>
    <div class="collection-check-box">
      <%= b.label %>
      <%= b.check_box %>
    </div>
  <% end %>
</fieldset>

app/views/admin/survey_templates/_form.html.erb
<p id="notice"><%= notice %></p>
  <% if @survey_template.errors.any? %>
    <div id="error_explanation" class="notification is-danger">
      <h2><%= pluralize(@survey_template.errors.count, "error") %> prohibited this survey_template from being saved:</h2>
        <ul>
        <% @survey_template.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag(:name, "Name:", :class => 'label') %>
    <div class="control">
      <%= form.text_field :name, id: :survey_template_name %>
    </div>
  </div>

  <div class="field">
    <div class="checkbox">
      <%= form.label :is_default, "Default Template" %>
      <%= form.check_box :is_default, id: :survey_template_is_default %>
    </div>
  </div>

  <div class="field">
    <%= form.fields_for :questions do |builder| %>
      <%= render 'question_fields', form: builder %>
    <% end %>
    <%= link_to_add_fields "Add Question", form, :questions %>
  </div>

  <div class="actions">
    <a class="button is-primary is-save">
      <%= form.submit 'Save Survey Template', :class => 'button is-transparent' %>
    </a>
  </div>

app/views/admin/survey_templates/_question_fields.html.erb
<fieldset>
  <div class="field">
    <%= form.hidden_field :_destroy %>
    <%= link_to " ", '#', class: "remove_fields fa fa-times-circle" %>
    <%= form.label :content, "Question", :class => 'label' %>
    <%= form.text_field :content %>
  </div>

  <%= form.label :question_type_id, "How many answers can this question have?", :class => 'label' %>
  <div class="select">
    <%= form.collection_select :question_type_id, QuestionType.all, :id, :label %>
  </div>

  <%= form.label "Answers", :class => 'label' %>
  <%= form.fields_for :answers do |builder| %>
    <%= render 'answer_fields', form: builder %>
  <% end %>
  <%= link_to_add_fields "Add Answer", form, :answers %>
</fieldset>

app/views/admin/survey_templates/edit.html.erb
<h1 class="title">Editing Survey Template <%= link_to 'Back to All Survey Templates', admin_survey_templates_path, :class => 'button is-blue is-back is-pulled-right large-button' %></h1>

<section>
  <%= form_for @survey_template, url: admin_survey_template_path(@survey_template) do |form| %>
    <%= render 'form', :form => form %>
  <% end %>
</section>

app/views/admin/survey_templates/index.html.erb
<% if notice %>
<p id="notice" class="notification is-success"><%= notice %></p>
<% end %>

<h1 class="title">Survey Templates</h1>

<% if !@survey_templates.empty? %>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Default</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @survey_templates.each do |survey_template| %>
        <tr>
          <td data-label="Name"><%= survey_template.name %></td>
          <td data-label="Default"><% if survey_template.is_default %><span class="fa fa-check"></span><%else%><span class="fa fa-times"><span><% end %> </td>
          <td class="stacked-button">
            <% if survey_template.is_default %>
              <%= link_to 'Set As Default', admin_survey_template_toggle_default_path(survey_template.id), :class => 'button is-default large-button', :disabled => true %>
            <% else %>
              <%= link_to 'Set As Default', admin_survey_template_toggle_default_path(survey_template.id), :class => 'button is-default large-button' %>
            <% end %>
            <%= link_to 'View', admin_survey_template_path(survey_template), :class => 'button show is-primary is-show large-button' %>
            <%= link_to 'Edit', edit_admin_survey_template_path(survey_template), :class => 'button edit is-gray is-edit large-button' %>
            <%= link_to 'Delete', admin_survey_template_path(survey_template), method: :delete, data: { confirm: 'Are you sure you want to delete this survey template?' }, :class => 'button is-red is-delete large-button' %>

          </td>
        </tr>
      <% end %>
      <tr>
        <td colspan=3>
          <%= link_to 'New Survey Template', new_admin_survey_template_path, :class => 'button is-warning is-add large-button' %>
        </td>
      </tr>
    </tbody>
  </table>
<% else %>
  <p>
    No survey templates have been created yet.
  </p>
<% end %>

<br>

app/views/admin/survey_templates/new.html.erb
<h1 class="title">New Survey Template<%= link_to 'Back to All Survey Templates', admin_survey_templates_path, :class => 'button is-blue is-back is-pulled-right large-button' %></h1>

<section>
  <%= form_for [:admin, @survey_template] do |form| %>
    <%= render "form", :form => form %>
  <% end %>
</section>

app/views/admin/survey_templates/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">
  Name:
  <%= @survey_template.name %>
  <%= link_to 'Back to All Survey Templates', admin_survey_templates_path, :class => 'button is-blue is-back is-pulled-right' %>
</h1>
<section class="question-list">
  <ol class="questions">
    <% @survey_template.questions.each do |question| %>
      <li>
        <%= question.content %>
        <ul class="answers">
          <% question.answers.each do |answer| %>
            <% label_ids = [] %>
            <% AnswersLabel.where(:answer_id => answer.id).each do |label| %>
              <% label_ids.push label.label_id %>
            <% end %>
            <div>
            <li><%= answer.content %></li>
            <%= collection_check_boxes :label, :label_ids, Label.where(id: label_ids), :id, :name, { disabled: -> (name) {true} }, {class: 'collection-check-box'} do |b| %>
              <div class="collection-check-box selected">
                <%= b.label %>
                <%= b.check_box %>
              </div>
            <% end %>
           </div>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ol>
  <%= link_to 'Edit', edit_admin_survey_template_path(@survey_template), :class => 'button is-gray is-edit' %>
</section>